### ISSUE TITLE
Need to escape quotes

### ISSUE THREAD

**Issue by christeredvartsen** [christeredvartsen/circleci-persist-env-vars-orb#1]
The following step:

```yaml
env/set-env-var:
    - var-name: SOME_VAR
    - var-value: some value
```

ends up as:

    export SOME_VAR=some value

`some value` should be enclosed in quotes.
